# Site settings
title: EHRI Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  EHRI documentation, mostly technical.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://EHRI.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  EHRI

# Build settings
markdown: kramdown
